### ISSUE TITLE
download anchor attribute не работает?

### ISSUE THREAD

**Issue by OpossumPetya** [coderaiser/vksave#2]
Почему-то  при скачивании имя файла не artist + name + '.mp3' , а рандомная строка + mp3. те download attrib не помогает. хотя работает на других сайтах.

**Comment by OpossumPetya** [comment]
погуглил, похоже это security measure, для скачек со сторонних сайтов.

**Comment by coderaiser** [comment]
Да, все верно. Будут идеи как исправить - присылай пул риквест.
